# Generated by Django 5.2.10 on 2026-02-02 12:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('food_type', models.CharField(choices=[('de_base', 'De base'), ('cuisine', 'Cuisine'), ('transforme', 'Transforme')], max_length=20)),
                ('kcal_100g', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)])),
                ('protein_g_100g', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)])),
                ('carbs_g_100g', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)])),
                ('fat_g_100g', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)])),
                ('vegan', models.BooleanField(default=False)),
                ('vegetarian', models.BooleanField(default=False)),
                ('pescetarian', models.BooleanField(default=False)),
                ('irritable_bowel', models.BooleanField(default=False)),
                ('gluten_free', models.BooleanField(default=False)),
                ('lactose_free', models.BooleanField(default=False)),
                ('barcode', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='fooditem_name_idx'), models.Index(fields=['barcode'], name='fooditem_barcode_idx')],
            },
        ),
    ]
