# Generated by Django 5.2.10 on 2026-02-02 12:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='fiber_g_100g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='group_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='group_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='salt_g_100g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='saturated_fat_g_100g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='source_code',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='subgroup_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='subgroup_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='subsubgroup_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='subsubgroup_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='sugars_g_100g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='water_g_100g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='food_type',
            field=models.CharField(choices=[('de_base', 'De base'), ('cuisine', 'Cuisine'), ('transforme', 'Transforme')], default='de_base', max_length=20),
        ),
    ]
