# Generated by Django 5.2.10 on 2026-02-02 12:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_fooditem_fiber_g_100g_fooditem_group_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='irritable_bowel',
        ),
        migrations.AddField(
            model_name='fooditem',
            name='irritability_level',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)]),
        ),
    ]
