# Generated by Django 5.2.10 on 2026-02-03 00:00

from django.db import migrations, models


def set_source(apps, schema_editor):
    FoodItem = apps.get_model("foods", "FoodItem")
    FoodItem.objects.filter(source_code__isnull=False).update(source="ciqual")
    FoodItem.objects.filter(source_code__isnull=True).update(source="manual")


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0002_fooditem_fiber_g_100g_fooditem_group_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fooditem",
            name="source",
            field=models.CharField(
                choices=[
                    ("ciqual", "Ciqual"),
                    ("openfoodfacts", "Open Food Facts"),
                    ("manual", "Manual"),
                ],
                default="manual",
                max_length=32,
            ),
        ),
        migrations.RunPython(set_source, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="fooditem",
            name="food_type",
        ),
    ]
