# Generated by Django 5.2.10 on 2026-02-02 12:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_remove_fooditem_irritable_bowel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='barcode',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{8,14}$', 'Barcode must be 8 to 14 digits (EAN/GTIN).')]),
        ),
    ]
