# Generated by Django 5.2.10 on 2026-02-03 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_fooditem_source_remove_food_type'),
        ('foods', '0005_alter_fooditem_carbs_g_100g_and_more'),
    ]

    operations = [
    ]
