# Generated by Django 5.2.10 on 2026-02-03 13:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0006_merge_20260203_1033"),
    ]

    operations = [
        migrations.AddField(
            model_name="fooditem",
            name="allergens_tags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="fooditem",
            name="brand",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="fooditem",
            name="categories_tags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="fooditem",
            name="ingredients_analysis_tags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="fooditem",
            name="ingredients_from_palm_oil_tags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="fooditem",
            name="ingredients_may_be_from_palm_oil_tags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="fooditem",
            name="ingredients_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fooditem",
            name="ingredients_text_fr",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fooditem",
            name="labels_tags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="fooditem",
            name="nutrition_per",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="fooditem",
            name="nutrient_levels",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="fooditem",
            name="nutriscore_grade",
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name="fooditem",
            name="nutriscore_score",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fooditem",
            name="nutriscore_version",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="fooditem",
            name="quantity",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="fooditem",
            name="source_completeness",
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name="fooditem",
            name="source_last_updated_t",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="fooditem",
            name="carbs_g_100g",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=7,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="fooditem",
            name="fat_g_100g",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=7,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="fooditem",
            name="kcal_100g",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=7,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1000),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="fooditem",
            name="protein_g_100g",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=7,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
