# Generated by Django 5.2.10 on 2026-02-03 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0007_fooditem_openfoodfacts_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fooditem",
            name="nutriscore_grade",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
