# Generated by Django 5.2.10 on 2026-02-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0008_alter_fooditem_nutriscore_grade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fooditem",
            name="quantity",
            field=models.TextField(blank=True, null=True),
        ),
    ]
