# Generated by Django 5.2.10 on 2026-02-03 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0009_alter_fooditem_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fooditem",
            name="brand",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="fooditem",
            name="name",
            field=models.TextField(),
        ),
    ]
