# Generated by Django 5.2.10 on 2026-02-03 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0010_alter_fooditem_name_and_brand"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fooditem",
            name="barcode",
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
