# Generated by Django 5.2.10 on 2026-02-05 00:00

from django.db import migrations, models


def forwards(apps, schema_editor):
    FoodItem = apps.get_model("foods", "FoodItem")
    FoodItem.objects.filter(irritability_level="0").update(irritability_level=None)
    FoodItem.objects.filter(irritability_level="1").update(irritability_level="low_fodmap")
    FoodItem.objects.filter(irritability_level__in=["2", "3"]).update(irritability_level="high_fodmap")


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0011_alter_fooditem_barcode_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fooditem",
            name="irritability_level",
            field=models.CharField(
                blank=True,
                choices=[("high_fodmap", "Riche en FODMAP"), ("low_fodmap", "Pauvre en FODMAP")],
                max_length=16,
                null=True,
            ),
        ),
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
