# Generated by Django 5.2.10 on 2026-02-05 00:00

from django.db import migrations, models


def forwards(apps, schema_editor):
    UserProfile = apps.get_model("users", "UserProfile")
    UserProfile.objects.filter(irritability_level="0").update(irritability_level=None)
    UserProfile.objects.filter(irritability_level="1").update(irritability_level="low_fodmap")
    UserProfile.objects.filter(irritability_level__in=["2", "3"]).update(irritability_level="high_fodmap")


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="irritability_level",
            field=models.CharField(
                blank=True,
                choices=[("high_fodmap", "Riche en FODMAP"), ("low_fodmap", "Pauvre en FODMAP")],
                max_length=16,
                null=True,
            ),
        ),
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
