# Generated by Django 5.2.10 on 2026-02-05 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_userprofile_irritability_level"),
        ("users", "0002_userprofile_allergens_filter"),
    ]

    operations = []
